# Generated by Django 2.1.5 on 2020-11-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclegroup',
            name='vehiclegroup_user',
        ),
    ]
