# Generated by Django 2.0 on 2020-10-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'managed': True, 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
