# Generated by Django 2.1.5 on 2020-11-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_vehiclegroup_vehiclegroup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclegroup',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
