# Generated by Django 2.0 on 2020-10-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20201030_1124'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addresses',
            table='addresses',
        ),
        migrations.AlterModelTable(
            name='allocation',
            table='allocation',
        ),
        migrations.AlterModelTable(
            name='bookingsmeta',
            table='bookings_meta',
        ),
    ]
