# Generated by Django 2.0 on 2020-10-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20201027_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'managed': True, 'verbose_name': 'Allocation', 'verbose_name_plural': 'Allocations'},
        ),
        migrations.AlterModelOptions(
            name='apisettings',
            options={'managed': True, 'verbose_name': 'Api_Setting', 'verbose_name_plural': 'Api_Settings'},
        ),
        migrations.AlterModelOptions(
            name='authgroup',
            options={'managed': True, 'verbose_name': 'AuthGroup', 'verbose_name_plural': 'AuthGroups'},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={'managed': True, 'verbose_name': 'Auth_group_permission', 'verbose_name_plural': 'Auth_group_permissions'},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={'managed': True, 'verbose_name': 'Auth_Permission', 'verbose_name_plural': 'Auth_Permissions'},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True, 'verbose_name': 'Auth User', 'verbose_name_plural': 'Auth Users'},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={'managed': True, 'verbose_name': 'Auth User Group', 'verbose_name_plural': 'Auth User Groups'},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={'managed': True, 'verbose_name': 'Auth User User Permission', 'verbose_name_plural': 'Auth User User Permissions'},
        ),
        migrations.AlterModelOptions(
            name='bookingincome',
            options={'managed': True, 'verbose_name': 'Booking Income'},
        ),
        migrations.AlterModelOptions(
            name='bookingsmeta',
            options={'managed': True, 'verbose_name': 'Bookings Meta', 'verbose_name_plural': 'Bookings Meta'},
        ),
        migrations.AlterModelOptions(
            name='drivervehicle',
            options={'managed': True, 'verbose_name_plural': 'DriverVehicles'},
        ),
        migrations.AlterModelOptions(
            name='faresettings',
            options={'managed': True, 'verbose_name': 'Fare Setting', 'verbose_name_plural': 'Fare Settings'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'managed': True, 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='reasons',
            options={'managed': True, 'verbose_name': 'Reason', 'verbose_name_plural': 'Reasons'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'managed': True, 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='serviceitems',
            options={'managed': True, 'verbose_name': 'Service Item', 'verbose_name_plural': 'Service Items'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='vehicles',
            options={'managed': True, 'verbose_name': 'Vehicle'},
        ),
        migrations.AlterModelOptions(
            name='vendors',
            options={'managed': True, 'verbose_name': 'Vendor'},
        ),
    ]
