# Generated by Django 2.1.5 on 2020-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20201124_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclegroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
