# Generated by Django 2.0 on 2020-11-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20201109_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_image',
            field=models.ImageField(blank=True, default='media/no-user.jpg', null=True, upload_to=''),
        ),
    ]
