# Generated by Django 2.1.5 on 2020-11-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20201124_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorders',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='workorders',
            name='wo_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.Vendors'),
        ),
    ]
