# Generated by Django 2.1.5 on 2020-11-24 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20201124_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='workorders',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.WorkOrderStatus'),
        ),
    ]
