# Generated by Django 2.0 on 2020-11-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20201110_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorders',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_id', to='transport.Vehicles'),
        ),
        migrations.AlterField(
            model_name='workorders',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_id', to='transport.Vendors'),
        ),
    ]
