# Generated by Django 2.0 on 2020-11-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20201111_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorders',
            options={'managed': True, 'verbose_name': 'Work Order', 'verbose_name_plural': 'Work Orders'},
        ),
    ]
