# Generated by Django 2.1.5 on 2020-11-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_auto_20201126_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.VendorType'),
        ),
    ]
