# Generated by Django 2.0 on 2020-11-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_auto_20201111_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='transport.Vehicles'),
        ),
    ]
