# Generated by Django 2.1.5 on 2020-11-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_auto_20201126_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
