# Generated by Django 2.0 on 2020-11-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_auto_20201111_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicles_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='transport.Users'),
        ),
    ]
