# Generated by Django 2.1.5 on 2020-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_auto_20201126_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='note_user',
            new_name='in_charge',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='note_customer',
        ),
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Hold', 'Hold')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='notes',
            name='submitted_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
