# Generated by Django 2.0 on 2020-11-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_auto_20201112_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereminder',
            name='servicereminder_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicereminders', to='transport.Users'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='settings_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='transport.Users'),
        ),
    ]
