# Generated by Django 2.1.5 on 2020-11-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_auto_20201126_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='transport.Users'),
        ),
    ]
