# Generated by Django 2.0 on 2020-11-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_auto_20201112_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereminder',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='transport.ServiceItems'),
        ),
        migrations.AlterField(
            model_name='servicereminder',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicleservice', to='transport.Vehicles'),
        ),
    ]
