# Generated by Django 2.1.5 on 2020-11-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_auto_20201126_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='submitted_on',
            field=models.DateField(),
        ),
    ]
