# Generated by Django 2.0 on 2020-11-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_auto_20201112_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereminder',
            name='servicereminder_user',
        ),
    ]
