# Generated by Django 2.1.5 on 2020-11-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_auto_20201126_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereminder',
            name='last_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='servicereminder',
            name='last_meter',
            field=models.IntegerField(),
        ),
    ]
