# Generated by Django 2.0 on 2020-11-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_remove_servicereminder_servicereminder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitems',
            name='serviceitem_user',
        ),
    ]
