# Generated by Django 2.0 on 2020-11-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_remove_serviceitems_serviceitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereminder',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
