# Generated by Django 2.1.5 on 2020-11-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_auto_20201127_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitems',
            name='meter_interval',
            field=models.CharField(blank=True, choices=[('On', 'On'), ('Off', 'Off')], default='off', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitems',
            name='time_interval',
            field=models.CharField(blank=True, choices=[('On', 'On'), ('Off', 'Off')], default='off', max_length=3, null=True),
        ),
    ]
