# Generated by Django 2.0 on 2020-11-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_auto_20201112_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitems',
            name='duesoon_meter',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitems',
            name='duesoon_time',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitems',
            name='overdue_meter',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitems',
            name='overdue_time',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
