# Generated by Django 2.1.5 on 2020-11-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_auto_20201127_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitems',
            name='duesoon_unit',
            field=models.CharField(blank=True, choices=[('days(s)', 'day(s)'), ('week(s)', 'week(s)'), ('month(s)', 'month(s)'), ('year(s)', 'year(s)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitems',
            name='overdue_unit',
            field=models.CharField(blank=True, choices=[('days(s)', 'day(s)'), ('week(s)', 'week(s)'), ('month(s)', 'month(s)'), ('year(s)', 'year(s)')], max_length=255, null=True),
        ),
    ]
