# Generated by Django 2.0 on 2020-11-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_auto_20201112_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitems',
            name='duesoon_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitems',
            name='overdue_meter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitems',
            name='overdue_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
