# Generated by Django 2.0 on 2020-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_auto_20201112_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faresettings',
            name='faresettings_user',
        ),
        migrations.AlterField(
            model_name='serviceitems',
            name='duesoon_meter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
