# Generated by Django 2.1.5 on 2020-11-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_auto_20201127_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitems',
            name='show_meter',
            field=models.CharField(blank=True, choices=[('On', 'On'), ('Off', 'Off')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitems',
            name='show_time',
            field=models.CharField(blank=True, choices=[('On', 'On'), ('Off', 'Off')], max_length=255, null=True),
        ),
    ]
