# Generated by Django 2.1.5 on 2020-11-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0018_auto_20201118_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
    ]
