# Generated by Django 2.1.5 on 2020-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0019_auto_20201118_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='api_token',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
    ]
