# Generated by Django 2.1.5 on 2020-12-14 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0020_auto_20201127_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='income_cat',
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='incomecat',
            name='user_id',
        ),
        migrations.AddField(
            model_name='income',
            name='income_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_category', to='transport.IncomeCat'),
        ),
        migrations.AddField(
            model_name='income',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='transport.Vehicles'),
        ),
        migrations.AlterField(
            model_name='incomecat',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
