# Generated by Django 2.1.5 on 2020-11-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0020_auto_20201118_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
