# Generated by Django 2.1.5 on 2020-12-15 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0021_auto_20201214_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_expense', to='transport.Vehicles'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_type', to='transport.ExpenseCat'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_expense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensecat',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
