# Generated by Django 2.1.5 on 2020-12-15 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0022_auto_20201215_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='bookings_user',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookings',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookings',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='payment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Completed', 'Not Completed'), ('Completed', 'Completed')], default='off', max_length=15, null=True),
        ),
    ]
