# Generated by Django 2.1.5 on 2020-12-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0027_auto_20201216_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='dest_addr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pickup_addr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
