# Generated by Django 2.1.5 on 2020-12-16 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0028_auto_20201216_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='pickup',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
