# Generated by Django 2.1.5 on 2020-12-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0032_auto_20201216_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='cost_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
