# Generated by Django 2.1.5 on 2020-12-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0034_auto_20201216_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecat',
            name='expensecat_user',
        ),
        migrations.RemoveField(
            model_name='expensecat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='expensecat',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='incomecat',
            name='incomecat_user',
        ),
        migrations.RemoveField(
            model_name='incomecat',
            name='name',
        ),
    ]
