# Generated by Django 2.1.5 on 2020-12-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0036_remove_reasons_reasons_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecat',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incomecat',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
